name: "Checkout action workflow"
on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - run: |
          ls -la
          ls -la .github/