on:
    workflow_dispatch:
jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
            - name: "Say hello friends"
              run: |
                "echo Hello Friends !!!!!!!!!!!!!!!!!"