name: "Build and  Push image to DockerHub"

on: 
    push:
        branches:
            - main
jobs:
    push_image:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Check credentials"
              run: |
                echo "${{ secrets.DOCKERHUB_USERNAME }}"

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: ./python/
                push: true
                tags: '${{ secrets.DOCKERHUB_USERNAME }}/flask-app:v1'